### ISSUE TITLE
这个可以在pc跑吗？

### ISSUE THREAD

**Issue by StrangeClow** [F-loat/ithome-lite#1]
请问这个可以在pc跑吗？ vuejs版的   谢谢

**Comment by F-loat** [comment]
微信开发者工具里可以，浏览器目前不行，需要改下配置，另外处理下小程序特有的 api，等后面小程序基本开发完成后，会试着生成网页版的，官方目前好像也准备做小程序和网页的兼容层

**Comment by StrangeClow** [comment]
谢谢
