### ISSUE TITLE
打包完，项目不能启动，文件找不到

### ISSUE THREAD

**Issue by zouqilai** [F-loat/ithome-lite#10]
打包完，项目不能启动，文件找不到

**Comment by F-loat** [comment]
可以详细描述下嘛，我这边打包运行没问题的，目录要选 dist

**Comment by umphp** [comment]
我都跑不动~~~

**Comment by F-loat** [comment]
你把错误发一下

**Comment by zouqilai** [comment]
1、git clone .....
2、npm install
3、在根目录创建一个project.config.js，内容如下
{
	"description": "项目配置文件。",
	"setting": {
		"urlCheck": false,
		"es6": true,
		"postcss": true,
		"minified": true,
		"newFeature": true
	},
	"miniprogramRoot": "./dist/",
	"compileType": "miniprogram",
	"appid": "wxfb63c03182e6d9cf",
	"projectname": "ithome-lite",
	"condition": {
		"search": {
			"current": -1,
			"list": []
		},
		"conversation": {
			"current": -1,
			"list": []
		},
		"game": {
			"currentL": -1,
			"list": []
		},
		"miniprogram": {
			"current": -1,
			"list": []
		}
	}
}
4、npm run build 我到这里报错
    报错：../../static/css/pages/news/common.wxss 报文件找不到，打包完后目录根本没有这个文件
    我重新在微信开发者工具删除没有appid的此项目，在重新创建一个有appid的项目，成功，问题解决

**Comment by F-loat** [comment]
嗯，最新的添加了开发工具的配置文件，重新导入应该就没问题
