### ISSUE TITLE
npm run dev跑不动~！提示缺少loader 

### ISSUE THREAD

**Issue by umphp** [F-loat/ithome-lite#11]
error  in ./node_modules/_mpvue-entry@0.4.1@mpvue-entry/dist/QuanziDetail.js

Module parse failed: Unexpected token (11:2)
You may need an appropriate loader to handle this file type.

**Comment by F-loat** [comment]
用 npm 安装，cnpm 晚点我再测试下

**Comment by F-loat** [comment]
错误信息你自己大概也看一下吧。。

**Comment by F-loat** [comment]
重新 clone 下，应该没这样问题了
