### ISSUE TITLE
路由第一个，只要一修改，热更新就失效

### ISSUE THREAD

**Issue by umphp** [F-loat/ithome-lite#12]

**Comment by F-loat** [comment]
可以具体描述下是做了什么修改，然后导致什么无法热更新吗

**Comment by umphp** [comment]
增加一个首页面路由，npm run dev 编译正常，开发者工具报File not found:.....

**Comment by umphp** [comment]
反正只要修改第一个的路由，热更新就失效，改什么也没用。

**Comment by umphp** [comment]
源文件里存在，但是热更新没起作用，没生成文件，因而没有些文件。

**Comment by umphp** [comment]
删除加入的路由，还原回原来正常的修改，问题依旧。

**Comment by F-loat** [comment]
你用的是最新 clone 的不，之前的不支持新增页面热更新的

**Comment by umphp** [comment]
同步后，问题修复了。
