### ISSUE TITLE
building for production...

### ISSUE THREAD

**Issue by umphp** [F-loat/ithome-lite#13]
增加路由后，再npm run build 或者 dev ，会一直死在building for production...这条命令行中，不动。

**Comment by umphp** [comment]
dev就是停留在 node build/dev-server.js

**Comment by F-loat** [comment]
重新安装依赖试试

**Comment by LOWINC** [comment]
"mpvue-loader": "1.0.12" 试下

**Comment by umphp** [comment]
重新安装依赖，及换"mpvue-loader": "1.0.12" 后重新安装，问题如故。

**Comment by umphp** [comment]
eslint --ext .js,.vue src 也没有语法错误

**Comment by F-loat** [comment]
增加了路由具体是做了什么

**Comment by umphp** [comment]
更新了"mpvue-entry": "^1.1.7",问题依旧存在。

**Comment by F-loat** [comment]
你调试下是卡在哪儿了？

**Comment by umphp** [comment]
要不我传到github上看看

**Comment by umphp** [comment]
https://github.com/umphp/wxappex

**Comment by umphp** [comment]
https://github.com/umphp/wxappex

**Comment by umphp** [comment]
难道是环境问题？我是cnpm,node8.9

**Comment by umphp** [comment]
win7系统

**Comment by umphp** [comment]
小程序开发者工具中，是否显示缺少文件？

**Comment by F-loat** [comment]
用 npm 试下

**Comment by umphp** [comment]
$ npm i
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> uglifyjs-webpack-plugin@0.4.6 postinstall F:\wxapp\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vue-loader@13.7.1 requires a peer of vue-template-compiler@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1103 packages in 91.05s

**Comment by umphp** [comment]
问题依旧

**Comment by F-loat** [comment]
你用官方模板创建个项目看有问题没

**Comment by umphp** [comment]
官方模板，用main.js，没用路由时，正常。

**Comment by F-loat** [comment]
你配置 mpvue-entry 后就会出问题？

**Comment by umphp** [comment]
应该就是mpvue-entry对win的支持度出问题。增加路由，删除后，依旧还会有删除的文件路径存在，在工具只打开，还会找已经删除的文件。

**Comment by F-loat** [comment]
我的 win10 是没问题的，你查看下 app.json ，路由删除后应该是会更新的

**Comment by umphp** [comment]
问题已解决，原因.vue文件，如果没有 export default {｝ 则路由会出问题，并run dev时会卡着不动。

**Comment by F-loat** [comment]
这个去 mpvue 提一下吧
