### ISSUE TITLE
.redbg(style="background-image: url('/static/assets/beijing@2x.png')")

### ISSUE THREAD

**Issue by umphp** [F-loat/ithome-lite#15]
微信开发工具上，背景有显示。手机上浏览时，背景图片不显示。

**Comment by F-loat** [comment]
背景图不支持本地图片，可以改用线上的，或者使用相对路径，然后调整 limit 配置，通过 webpack 转换为 base64 格式

**Comment by umphp** [comment]
但是换成这样，.redbg(style="background-image: url('static/assets/beijing@2x.png')")，开发者工具不显示，手机却能显示

**Comment by F-loat** [comment]
小程序的问题，自己搜索解决吧 https://segmentfault.com/q/1010000010488479
