### ISSUE TITLE
加载更多api

### ISSUE THREAD

**Issue by 0312birdzhang** [F-loat/ithome-lite#17]
首先感谢整理的api 👍 

发现了一个加载更多的api 
https://github.com/henta/news/blob/ef7f84339c6df8122bcf8dfef5cf0a01cc91933c/app/src/main/java/my/hhx/com/newpager/api/ITHomeApi.java
https://github.com/henta/news/blob/master/app/src/main/java/my/hhx/com/newpager/util/ITHomeUtils.java

😂 需要用js重写一下des加密的部分

**Comment by 0312birdzhang** [comment]
已完成： https://github.com/0312birdzhang/harbour-aitizhijia/blob/master/qml/js/api.js#L33

**Comment by F-loat** [comment]
业务部分不准备再更新了
