### ISSUE TITLE
关于获取具体新闻的评论

### ISSUE THREAD

**Issue by small2Sun** [F-loat/ithome-lite#19]
最热评论 https://dyn.ithome.com/json/hotcommentlist/350/87a8e5b144d81938.json
评论列表 https://dyn.ithome.com/json/commentlist/350/87a8e5b144d81938.json
评论详情 https://dyn.ithome.com/json/commentcontent/d739ee8f2ceb0a27.json

.json前面的值代表什么呢

**Comment by F-loat** [comment]
文章的 id 吧，列表页中可以拿到
