### ISSUE TITLE
体验者账号申请

### ISSUE THREAD

**Issue by F-loat** [F-loat/ithome-lite#2]
这个小程序属于 文娱-资讯 类，所以个人账号无法通过审核，想要体验的人可以留下你的微信 ID，然后我把你加入体验者列表，这样就可以使用体验版小程序了
![qrcode_beta](https://user-images.githubusercontent.com/16759376/37383349-2fcf4ee6-2783-11e8-811f-0046ace76c13.jpg)

**Comment by smallTeletubbies** [comment]
jxg18188

**Comment by JiaJun-yu** [comment]
Shakalakayjj

**Comment by EasonYou** [comment]
easonyouhehe

**Comment by forecho** [comment]
ipzone

**Comment by F-loat** [comment]
上面四位已经添加好了

**Comment by CodeNauhc** [comment]
codenahuc

**Comment by F-loat** [comment]
添加之后就删掉了啊

**Comment by geraldlrh** [comment]
geraldlrh

**Comment by hoganjobs** [comment]
hongju110

**Comment by iconben** [comment]
微信ID  benjamin_qin
谢谢！

**Comment by ryan-hung** [comment]
微信ID can170015419 谢谢！

**Comment by kimi2353** [comment]
chuangjun

**Comment by yangweijie** [comment]
yangweijiester

**Comment by iJzFan** [comment]
JzFan001

**Comment by lllidan120** [comment]
微信ID：MingYu-fly

**Comment by F-loat** [comment]
还剩最后一个名额啦

**Comment by duanpf** [comment]
微信ID:   weixin15225205434

**Comment by weicong** [comment]
weiconglive

**Comment by lwd5237** [comment]
lwd1059114363

**Comment by F-loat** [comment]
emmm名额满了已经

**Comment by luweiCN** [comment]
luwei_1280380446
