### ISSUE TITLE
你好请问如何编译出h5代码呢？

### ISSUE THREAD

**Issue by zhangjuanjuan01** [F-loat/ithome-lite#20]
如何配置才能编译出h5代码？还是已经写好了配置，那应该如何执行呢?

**Comment by F-loat** [comment]
另一个分支

**Comment by zhangjuanjuan01** [comment]
你是如何处理h5和小程序使用不同标签的呢？比如select和picker？

**Comment by F-loat** [comment]
这个项目里没用到这些，具体的做法基本就是两端各封装下 select ，以相同的方式调用，根据平台使用不同的组件
