### ISSUE TITLE
关于导入weui

### ISSUE THREAD

**Issue by yewang422** [F-loat/ithome-lite#21]
把weui.css放到static/weui 目录下
在main.js 里面使用
![image](https://user-images.githubusercontent.com/27805157/44480537-04b32080-a676-11e8-8f5d-bde92be65b80.png)
编译的时候报错
![image](https://user-images.githubusercontent.com/27805157/44480555-1399d300-a676-11e8-9718-ebac284b0ca1.png)

**Comment by yewang422** [comment]
TAT

**Comment by JokerLoLgrey** [comment]
使用小程序第三方库，比如iview，使用方法如下，在对应的main.js这么引用就行了
```
usingComponents: {
      'i-tab': '../../components/iview/tab/index',
      'i-tabs': '../../components/iview/tabs/index',
      'i-badge': '../../components/iview/badge/index',
      'i-message': '../../components/iview/message/index',
      'i-load-more': '../../components/iview/load-more/index'
    }
```

**Comment by F-loat** [comment]
引用文件尽量使用 '@/xxx' 形式的路径
