### ISSUE TITLE
这个clone下到本地后,如何编译在微信web开发工具运行?

### ISSUE THREAD

**Issue by lxk0301** [F-loat/ithome-lite#24]
你好,之前做的都是原生开发微信小程序,没使用过mpvue,  请问下载下来后,如何使用?

**Comment by F-loat** [comment]
建议先看下 mpvue 相关的文档。执行 npm i 安装依赖后，即可执行 npm run dev 进行开发，开发者工具选择项目目录即可，最后通过 npm run build 进行生产环境的打包
