### ISSUE TITLE
post请求Data会变成字符串

### ISSUE THREAD

**Issue by lxk0301** [F-loat/ithome-lite#26]
你好,我模拟你那边代码参数的get请求.  写了一个post请求.但是编译器里面的request Payload是字符串
下面是截图
你的get请求截图
![tim 20181019184555](https://user-images.githubusercontent.com/21308593/47214012-412d9f00-d3cf-11e8-8eb7-4fe411c2ff0f.png)
我模拟的POST请求截图
![snipaste_2018-10-19_18-47-08](https://user-images.githubusercontent.com/21308593/47214126-92d62980-d3cf-11e8-81b8-57a03f4084a1.png)
![snipaste_2018-10-19_18-43-19](https://user-images.githubusercontent.com/21308593/47214362-42ab9700-d3d0-11e8-8d28-1e97ecc7f464.png)

**Comment by F-loat** [comment]
请求库使用了 [flyio](https://wendux.github.io/dist/#/doc/flyio/readme) ，可以具体看下文档

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/47327519-2a719b80-d6a0-11e8-8ecb-028c9e0f6266.png)


> 请求库使用了[flyio](https://wendux.github.io/dist/#/doc/flyio/readme)，可以具体看下文档

@F-loat 看来,  但是 这边 第二个参数data,还是会变成字符串
![image](https://user-images.githubusercontent.com/21308593/47335176-8c3ffe80-d6bc-11e8-9d90-00fe9bdc17eb.png)
![image](https://user-images.githubusercontent.com/21308593/47335186-97932a00-d6bc-11e8-960b-167109bb2ce9.png)

**Comment by F-loat** [comment]
截图里这个不是对象吗，你看看是不是需要配置什么 header

**Comment by F-loat** [comment]
建议直接去 flyio 的仓库提问
