### ISSUE TITLE
.postcssrc.js 判断问题

### ISSUE THREAD

**Issue by appbest** [F-loat/ithome-lite#29]
.postcssrc.js

判断当前运行模式，
`process.env.MODE === 'h5'
`
process.env.MODE  这个参数，在哪里设置，demo中找不到

导致，一直执行 rem 转 rpx

**Comment by F-loat** [comment]
这个项目是通过 mpvue-packager 自动注入环境变量的，你可以直接使用 cross-env 配置

**Comment by F-loat** [comment]
使用了 mpvue-packager 的话，MODE 这个变量是会根据 --mode 参数变的，新的模板改动比较大，一直没更新，等弄好了会加个文档说明的

**Comment by F-loat** [comment]
mpvue-packager 目前的文档应该是足够支持小程序开发用的，web 版的还有点问题，所以也没细写

**Comment by F-loat** [comment]
相关文档已更新
