### ISSUE TITLE
部分接口参数问题

### ISSUE THREAD

**Issue by F-loat** [F-loat/ithome-lite#3]
新闻相关的接口有几个参数不太清楚是哪儿来的，有能力的人可以帮忙测下😋

**Comment by ryh** [comment]
```
  getRelatedNews: (id) => request.get(`https://api.ithome.com/json/tags/0${id.substr(0, 3)}/${id}.json`),

```
这么写刚开始可以，后来开发者工具又报错了

**Comment by F-loat** [comment]
什么错误啊

**Comment by ryh** [comment]
你现在的是：  getRelatedNews: (id) => request.get(`https://api.ithome.com/json/tags/0350/${id}.json`),

所以有些news ID为 非350开头的必定服务器报404
实际相关新闻的API地址是
```
https://api.ithome.com/json/tags/0{id前3位}/{id}.json
```

**Comment by F-loat** [comment]
嗯，这个接口我处理下，当时没直接这么写是因为大多数都是 350，另外不懂他为什么要这么设计。。

**Comment by F-loat** [comment]
@ryh 我这边的错误和请求库有关，返回值不是标准的 json 需要处理后再解析，给那边提了个 issue 了

**Comment by F-loat** [comment]
此项目仅作为 mpvue 开发示例，不再新增功能
