### ISSUE TITLE
请问修改了mpvue什么配置使其变成了ithome-lite能在h5运行？（除了微信小程序特有的API）

### ISSUE THREAD

**Issue by Seansun1314** [F-loat/ithome-lite#33]
请问能不能具体一些，比如像具体操作步骤，万分感谢了！mpvue没有提供，F-loat也没有细说，找不到相关博客说明……

**Comment by F-loat** [comment]
文章是有写过一篇的，不过比较旧了，你可以参考下 https://juejin.im/post/5ab84a33f265da239c7b56bd

**Comment by Seansun1314** [comment]
好的，非常感谢，我继续看一下
