### ISSUE TITLE
uni-app中创建wxcomponents文件夹引入小程序组件的问题

### ISSUE THREAD

**Issue by weiyunpeng** [F-loat/ithome-lite#34]
uni-app支持引入小程序原生组件，这里的例子支持[uni-app官方形式](https://uniapp.dcloud.io/frame?id=%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81)创建wxcomponents文件夹引入小程序原生组件么？

**Comment by F-loat** [comment]
应该是支持的，这个项目的 uni-app 版就是用他们官方的 cli 模板直接创建的

**Comment by weiyunpeng** [comment]
> 应该是支持的，这个项目的 uni-app 版就是用他们官方的 cli 模板直接创建的

那估计是他们平台的问题，我去问问。

**Comment by F-loat** [comment]
放在 src 目录下，这个其实就是他们根据平台加了不同的 copy 配置

**Comment by weiyunpeng** [comment]
> 放在 src 目录下，这个其实就是他们根据平台加了不同的 copy 配置

就是参考[官方demo](https://github.com/dcloudio/uni-app/tree/master/examples/wxcomponents-template)进行使用的，从dist里面看是copy过去了。刚刚发现应该是没有对其中的文件进行es6转es5，导致的无法运行，开启微信开发者工具的es6转es5就可以了。
