### ISSUE TITLE
请问使用mpvue可以同时开发h5和小程序吗

### ISSUE THREAD

**Issue by wangjiahan** [F-loat/ithome-lite#35]
我们公司现在让我们用mpvue同时开发h5和小程序  不知道是否可行  目前一直在踩坑  请大神指点一二  跪谢

**Comment by F-loat** [comment]
使用 mpvue 自行开发双端应用比较复杂，建议你直接使用 uniapp

**Comment by wangjiahan** [comment]
好的多谢🙏
