### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by Snnny** [F-loat/ithome-lite#6]
Module parse failed: C:\Users\xxbmm\Desktop\ithome-lite\node_modules\_mpvue-entr                                                                                           y@0.3.2@mpvue-entry\QuanziList.js Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
| const app = new Vue({
|   store,
|   ...App
| })
| app.$mount()

**Comment by F-loat** [comment]
你 clone 的是最新的版本吗，

**Comment by Snnny** [comment]
是的，刚拉下来的，node版本的问题吗？7.1.0和8.10.0都是这个问题

**Comment by F-loat** [comment]
应该不是 node 的问题，这部分代码正常的话会先由 babel 处理的，你有改过什么配置吗

**Comment by Snnny** [comment]
没有动，正常cnpm i 然后启动项目

**Comment by F-loat** [comment]
你试下用 npm 安装依赖，可能是 cnpm 导致的错误

**Comment by Snnny** [comment]
确实是好了，顺便问一下，我怎么才能用浏览器看？

**Comment by F-loat** [comment]
切换到 web-version 就是普通 vue 项目的代码了

**Comment by Snnny** [comment]
好的，感谢☺
