### ISSUE TITLE
mpvue-router-patch 引用的 query-string ios10版本兼容问题

### ISSUE THREAD

**Issue by ltinyho** [F-loat/ithome-lite#7]
![wechatimg1](https://user-images.githubusercontent.com/28479270/39823397-8ea215d8-53df-11e8-9909-2bb21ee4e71b.jpeg)
因为使用了`mpvue-router-patch`包，但是并没有经过`babel`处理，导致打包后的`vendor.js`包含`const`，经测试，在`ios` 10版本及以下会出现如图错误。

```
 {
        test: /\.js$/,
        loader: 'babel-loader?cacheDirectory=true',
        include: [
          /node_modules\/.*mpvue-router-patch.*/,
          // /node_modules\/.*query-string.*/,
        ],
      },
}
```
我的解决办法是使用`babel-loader`处理，但是`mpvue-router-patch`引用的`query-string`这个包也是使用了`const`，没有经过`babel`处理。我将`query-string`也同样处理后,但是`query-string`并不是使用`es6`写法，不知道怎么处理了。

`import queryString from 'query-string';`
`const queryStr = queryString.stringify(query, {
    encode: false
  })`

改为
`import queryString from 'querystring';`
 `const queryStr = queryString.stringify(query)`

我将`query-string`替换为`querystring`解决了兼容问题。请问怎样配置能解决这个问题的。

**Comment by ltinyho** [comment]
开发工具转es6会报错，因为我其他的包已经转过了，能提供es5版本的最好了

**Comment by F-loat** [comment]
这个库好说，组件库不知道有没有类似的问题

**Comment by F-loat** [comment]
可以换成 `querystring`，同时我这边也得转成 es5 吧

**Comment by ltinyho** [comment]
感谢

**Comment by F-loat** [comment]
好了应该，我这边简单测了下没问题

**Comment by ltinyho** [comment]
嗯嗯，成功解决兼容问题，👍。
