### ISSUE TITLE
clone master 的代码没有办法运行

### ISSUE THREAD

**Issue by ZhiGang-Fang** [F-loat/ithome-lite#8]
ERROR  Failed to compile with 5 errors                                                                                   #6 @F-loat                             10:17:56

 error  in ./node_modules/_mpvue-entry@0.3.7@mpvue-entry/dist/NewsList.js

Module parse failed: Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
| const app = new Vue({
|   store,
|   ...App
| })
| app.$mount()

**Comment by F-loat** [comment]
https://github.com/F-loat/mpvue-entry/issues/5
